### ISSUE TITLE
switch to another archlinux user package manager module due to permissions issues

### ISSUE THREAD

**Issue by mwilliammyers** [mkwmms/ansible-github#3]
Ref. [tasks/main.yml:17](https://github.com/mkwmms/ansible-github/blob/1025eec2ae35c84b2a33bb0d8331a084738de48c/tasks/main.yml#L17)

``` yml
  # FIXME: switch to another archlinux package manager module due to permissions issues
  - name: yaourt | github enchancers
    yaourt: name="{{ item }}"
    with_items: "{{ github_packages }}"
  when: ansible_distribution == 'Archlinux'
  # become: yes
…
```

yaourt does not handle permissions well - this will only work if the sudo cache is still valid see: ansible/ansible-modules-extras/pull/1104

**Comment by mkwmms** [comment]
Ref. [tasks/main.yml:17](https://github.com/mkwmms/ansible-github/blob/1025eec2ae35c84b2a33bb0d8331a084738de48c/tasks/main.yml#L17)

```yml
  # FIXME: switch to another archlinux package manager module due to permissions issues
  - name: yaourt | github enchancers
    yaourt: name="{{ item }}"
    with_items: "{{ github_packages }}"
  when: ansible_distribution == 'Archlinux'
  # become: yes
…
```

**Comment by mkwmms** [comment]
Ref. [tasks/main.yml:17](https://github.com/mkwmms/ansible-github/blob/baa2f24b891fdc67c228972c20127808c698eb59/tasks/main.yml#L17)

```yml
    # FIXME: switch to another archlinux package manager module due to permissions issues
    - name: yaourt | github enchancers
      yaourt: name="{{ item }}" state="{{ install_state }}"
      with_items: "{{ github_packages }}"
  when: ansible_distribution == 'Archlinux'
  # become: yes
…
```
